spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:tagreads}?createDatabaseIfNotExist=true&useSSL=true&sslMode=VERIFY_CA&enabledTLSProtocols=TLSv1.2,TLSv1.3&serverTimezone=UTC
    username: ${MYSQL_USER:appuser}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  flyway:
    enabled: true
    locations: classpath:db/migration/mysql
    baseline-on-migrate: true

# Run with profile "mysql" to activate JdbcTagReadRepository
